spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lab4
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create-drop

server:
  port: 27525
